### ISSUE TITLE
We lost all the issues/PRs from `bitcoind` repo

### ISSUE THREAD

**Issue by tcharding** [tcharding/rust-bitcoind-json-rpc#14]
When I imported `bitcoind`  (as `regtest/`) we lost all the open issues and PRs. Is that what I/we meant to do? Or should we:

- Manually triage them and bring over the ones we want
- Import everything

**Comment by tcharding** [comment]
Same consideration will apply to the upcoming import of `jsonrpc`. cc @apoelstra

**Comment by apoelstra** [comment]
PRs we can ignore. Glancing at the issues list there are a couple that we should maybe bring over but honestly we can probably ignore those as well. Both crates have a small list of very old issues, many of which are requests for architectural changes that likely won't be taken up.
